# Generated by Django 3.1.5 on 2021-01-26 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20210125_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=2000, verbose_name='Событие')),
                ('date_event', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_finish', models.TimeField()),
                ('type_of_remind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_event', to='reminder.typereminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CountryHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidays', models.TextField(null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_holiday', to='reminder.country')),
            ],
        ),
    ]
