# Generated by Django 3.1.5 on 2021-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_countryholiday_event_typereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryholiday',
            name='holiday_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='holiday_end',
            field=models.DateTimeField(null=True),
        ),
    ]
