# Generated by Django 3.1.5 on 2021-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20210127_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryholiday',
            name='holiday_begin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='countryholiday',
            name='holiday_end',
            field=models.DateField(null=True),
        ),
    ]
