# Generated by Django 3.1.5 on 2021-02-01 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_auto_20210130_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='remind',
            field=models.CharField(blank=True, choices=[(datetime.timedelta(seconds=3600), 'За час'), (datetime.timedelta(seconds=7200), 'За 2 часа'), (datetime.timedelta(seconds=14400), 'За 4 часа'), (datetime.timedelta(days=1), 'За день'), (datetime.timedelta(days=7), 'За неделю')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_remind',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
