# Generated by Django 3.1.5 on 2021-02-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_auto_20210201_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type_of_remind',
        ),
        migrations.DeleteModel(
            name='TypeReminder',
        ),
    ]
