# Generated by Django 3.1.5 on 2021-02-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_auto_20210201_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_event', to='reminder.event'),
        ),
    ]
