# Generated by Django 3.1.5 on 2021-02-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0010_event_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='events',
        ),
    ]
